package pan.alexander.filmrevealer.utils

const val FILMS_UPDATE_DEFAULT_PERIOD_MILLISECONDS = 5 * 60 * 1000
const val FIRST_PAGE_NUMBER = 1
const val MINIMUM_SCROLL_DIFFERENCE = 10
const val UPDATE_REQUEST_PREDICTION_ITEMS = 5
const val FILM_DETAILS_EXPIRE_PERIOD_MILLISECONDS = 5 * 24 * 60 * 60 * 1000L
const val FILMS_UPDATE_RETRIES_COUNT = 3
const val NETWORK_REQUEST_THROTTLE_TIME_MSEC = 300L
